version: "3"

tasks:
  release:
    cmds:
      - commit-and-tag-version
      - git push --follow-tags origin main
  build-production:
    cmds:
      - hugo --gc --minify --baseURL "https://cdn.improrama.de/"
  serve:
    cmds:
      - hugo server --buildDrafts --disableFastRender
